languages = {
    "af": "Afrikaans",
    "ar": "Arabic",
    "bn": "Bangla",
    "bs": "Bosnian (Latin)",
    "bg": "Bulgarian",
    "yue": "Cantonese (Traditional)",
    "ca": "Catalan",
    "zh-Hans": "Chinese Simplified",
    "zh-Hant": "Chinese Traditional",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "et": "Estonian",
    "fj": "Fijian",
    "fil": "Filipino",
    "fi": "Finnish",
    "fr": "French",
    "de": "German",
    "el": "Greek",
    "ht": "Haitian Creole",
    "he": "Hebrew",
    "hi": "Hindi",
    "mww": "Hmong Daw",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian",
    "ja": "Japanese",
    "sw": "Kiswahili",
    "tlh": "Klingon",
    "tlh-Qaak": "Klingon (pIqaD)",
    "ko": "Korean",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "mg": "Malagasy",
    "ms": "Malay",
    "mt": "Maltese",
    "nb": "Norwegian",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    "otq": "Querétaro Otomi",
    "ro": "Romanian",
    "ru": "Russian",
    "sm": "Samoan",
    "sr-Cyrl": "Serbian (Cyrillic)",
    "sr-Latn": "Serbian (Latin)",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sv": "Swedish",
    "ty": "Tahitian",
    "ta": "Tamil",
    "th": "Thai",
    "to": "Tongan",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "cy": "Welsh",
    "yua": "Yucatec Maya"
}
